services:
  rgit:
    build: .
    command:
      - "[::]:8000"
      - /git
      - -d /tmp/rgit-cache.db
      - --repository-list
      - /app/whitelist
    volumes:
      - ./git:/git
      - ./whitelist:/app/whitelist:ro
    ports:
      - 8000:8000
    environment:
      - REFRESH_INTERVAL=5m
    restart: unless-stopped
